
// Generated by Cadence Genus(TM) Synthesis Solution 19.12-s121_1
// Generated on: Oct 17 2021 15:59:35 IST (Oct 17 2021 10:29:35 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, out);
  input clk, rst;
  output [2:0] out;
  wire clk, rst;
  wire [2:0] out;
  wire n_0, n_1, n_2, n_4, n_5;
  DFQRM2RA \out_reg[2] (.RB (rst), .CK (clk), .D (n_5), .Q (out[2]));
  NR2M2R g88(.A (out[2]), .B (n_2), .Z (n_5));
  DFQRM2RA \out_reg[1] (.RB (rst), .CK (clk), .D (n_4), .Q (out[1]));
  NR2M2R g91(.A (out[2]), .B (n_1), .Z (n_4));
  DFQRM2RA \out_reg[0] (.RB (rst), .CK (clk), .D (n_0), .Q (out[0]));
  XNR2M2RA g93(.A (out[0]), .B (out[1]), .Z (n_1));
  NR2M2R g94(.A (out[2]), .B (out[0]), .Z (n_0));
  ND2M2R g95(.A (out[0]), .B (out[1]), .Z (n_2));
endmodule

